name: Validate pull requests to master

on:
  pull_request:
    branches: [ master ]

env:
  APP_PORT: ${{ APP_PORT }}
  DB_CONNECTION_URI: ${{ DB_CONNECTION_URI }}
  JSON_WEBTOKEN_SECRET: ${{ JSON_WEBTOKEN_SECRET }}
  SEND_MAIL_FROM: ${{ SEND_MAIL_FROM }}
  SMTP_MAIL_HOST: ${{ SMTP_MAIL_HOST }}
  SMTP_MAIL_PORT: ${{ SMTP_MAIL_PORT }}
  MAIL_AUTH_USER: ${{ MAIL_AUTH_USER }}
  MAIL_AUTH_PASSWORD: ${{ MAIL_AUTH_PASSWORD }}
  APP_NAME: ${{ APP_NAME }}
  API_BASEURL: ${{ API_BASEURL }}
  API_MAILLOGO: ${{ API_MAILLOGO }}

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
